// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXdHUTbO521VhaDxtjicsVUM9TVvCfGg',
    appId: '1:585267890180:web:7a5fd0b9b4a981f90a8d51',
    messagingSenderId: '585267890180',
    projectId: 'chat-application-e5133',
    authDomain: 'chat-application-e5133.firebaseapp.com',
    storageBucket: 'chat-application-e5133.firebasestorage.app',
    measurementId: 'G-FKHZCDY3SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH0fXZrVf0t2oJvyKXe85zZxZ_GsWONns',
    appId: '1:585267890180:android:537526597faed3210a8d51',
    messagingSenderId: '585267890180',
    projectId: 'chat-application-e5133',
    storageBucket: 'chat-application-e5133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9U9EFO9WHyAn5AONdqYBoGjCBbDCsFNE',
    appId: '1:585267890180:ios:617e9aae9aa4305d0a8d51',
    messagingSenderId: '585267890180',
    projectId: 'chat-application-e5133',
    storageBucket: 'chat-application-e5133.firebasestorage.app',
    iosBundleId: 'com.example.whatsappUiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9U9EFO9WHyAn5AONdqYBoGjCBbDCsFNE',
    appId: '1:585267890180:ios:617e9aae9aa4305d0a8d51',
    messagingSenderId: '585267890180',
    projectId: 'chat-application-e5133',
    storageBucket: 'chat-application-e5133.firebasestorage.app',
    iosBundleId: 'com.example.whatsappUiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxXdHUTbO521VhaDxtjicsVUM9TVvCfGg',
    appId: '1:585267890180:web:7c2658622b0ecf4d0a8d51',
    messagingSenderId: '585267890180',
    projectId: 'chat-application-e5133',
    authDomain: 'chat-application-e5133.firebaseapp.com',
    storageBucket: 'chat-application-e5133.firebasestorage.app',
    measurementId: 'G-TBMW37H9KV',
  );

}